server:
  port: 8002
spring:
  application:
    name: business-modular-hi
  zipkin:
    base-url: http://192.168.79.130:9411
  #数据库连接配置
  datasource:
    #数据库连接
    url: jdbc:mysql://192.168.79.130:3306/Maker_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #用户名密码
    username: root
    password: Ai1314520..
    #驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/