server:
  port: 8763
spring:
  application:
    name: service-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/hjs785053766/hjs785053766
          searchPaths: respo
          username: hjs785053766
          password: Ai1314520..
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/