server:
  port: 8003
spring:
  application:
    name: business-modular-feign
  zipkin:
    base-url: http://192.168.79.130:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/