# web port
server:
  port: 8765
  # no web
  #spring.main.web-environment=false
  # log config
  #logging:
  #  config: classpath:logback.xml
  ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://192.168.79.130:8760/xxl-job-admin
    executor:
      appname: service-timer

