eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-auth
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: null     # 密码,默认密码为空
    timeout: 10000
    database: 0         # Redis数据库索引（默认为0）,如果设置为1，那么存入的key-value都存放在select 1中
    max-wait: 30000     # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-active: 100     # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 20        # 连接池中的最大空闲连接
    min-idle: 0         # 连接池中的最小空闲连接
      #cluster:           # 集群配置
      #nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
    #max-redirects: 2  # 最大重定向次数
  devtools:
    restart:
      enabled: false
  datasource:
    #数据库连接
    url: jdbc:mysql://192.168.79.130:3306/sys_auth?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    #用户名密码
    username: root
    password: Ai1314520..
    #驱动包
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: 35713a66d8a9123a119633448cd859a4
  # 有效期，单位秒，默认2周
  expirationTimeInSecond: 89280
Base64:
  key: 24f42dfc8c4ba981493ae57425f409b3
mybatis-plus:
  mapper-locations: classpath*:com/forezp/api/mapper/**/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl